[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 声话同步

## 摘要

### FoleyCrafter 包含两个关键组件：

#### 用于语义对齐的语义适配器和

##### 语义适配器利用并行交叉注意力层根据视频特征来调整音频生成，从而产生与视觉内容在语义上相关的逼真音效

#### 用于精确音视频同步的时间控制器。

##### 时间控制器结合了起始点检测器和基于时间戳的适配器来实现精确的音视频对齐

### FoleyCrafter 的一个显著优势是它与文本提示兼容，

#### 能够根据用户意图使用文本描述来实现可控且多样的视频到音频的生成

### 我们在标准基准上进行了大量的定量和定性实验，以验证 FoleyCrafter 的有效性
